import { useCallback, useState } from "react";
import { Button } from "@/components/ui/button";
import { type Prediction, generateUncertaintySummary, dataSources } from "@/data/mockData";
import { Download, FileText, Loader2 } from "lucide-react";

interface Props {
  prediction: Prediction;
}

function formatSection(title: string, content: string): string {
  return `\n${"=".repeat(60)}\n${title.toUpperCase()}\n${"=".repeat(60)}\n\n${content}\n`;
}

function generateReport(p: Prediction): string {
  const summary = generateUncertaintySummary(p);
  const now = new Date().toISOString().slice(0, 16).replace("T", " ");

  let report = "";

  // Header
  report += "╔══════════════════════════════════════════════════════════╗\n";
  report += "║           ATLAS — Uncertainty Modeling Report           ║\n";
  report += "╚══════════════════════════════════════════════════════════╝\n\n";
  report += `Generated: ${now}\n`;
  report += `Prediction: ${p.title}\n`;
  report += `Region: ${p.region}\n`;
  report += `Forecast Window: ${p.forecastWindow}\n`;
  report += `Last Updated: ${p.lastUpdate}\n`;

  // Executive Summary
  report += formatSection("Executive Summary", summary);

  // Key Metrics
  const metrics = [
    `Probability Score:       ${p.probability}%`,
    `Confidence Level:        ${p.confidence.toUpperCase()}`,
    `Data Completeness:       ${p.dataCompleteness}%`,
    `Model Agreement:         ${(p.modelAgreement * 100).toFixed(0)}%`,
    `Epistemic Uncertainty:   ${(p.epistemicUncertainty * 100).toFixed(0)}% (missing knowledge)`,
    `Aleatoric Uncertainty:   ${(p.aleatoricUncertainty * 100).toFixed(0)}% (natural variability)`,
    `Freshness Score:         ${(p.freshnessScore * 100).toFixed(0)}%`,
    `Population Exposure:     ${(p.populationExposure / 1000000).toFixed(1)}M`,
    `Uncertainty Source:      ${p.uncertaintySource}`,
  ].join("\n");
  report += formatSection("Key Metrics", metrics);

  // Contributing Variables
  const vars = p.contributingVariables
    .sort((a, b) => b.weight - a.weight)
    .map((v, i) => `  ${i + 1}. ${v.name.padEnd(30)} Weight: ${(v.weight * 100).toFixed(0)}%  Status: ${v.status}`)
    .join("\n");
  report += formatSection("Contributing Variables", vars);

  // Historical Accuracy
  const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  const accuracy = p.historicalAccuracy
    .map((val, i) => `  ${months[i % 12].padEnd(6)} ${val}%  ${"█".repeat(Math.round(val / 5))}`)
    .join("\n");
  const avgAcc = Math.round(p.historicalAccuracy.reduce((a, b) => a + b, 0) / p.historicalAccuracy.length);
  report += formatSection("Historical Accuracy", `Average: ${avgAcc}%\n\n${accuracy}`);

  // Data Source Coverage
  const sources = dataSources
    .map((s) => `  ${s.name.padEnd(25)} Coverage: ${String(s.coverage).padStart(3)}%  Status: ${s.status.padEnd(8)} Latency: ${s.latency}`)
    .join("\n");
  report += formatSection("Data Source Coverage", sources);

  // Audit Trail
  const audit = p.auditTrail
    .map((e) => `  [${e.timestamp}]  ${e.action}\n    ${e.detail}`)
    .join("\n\n");
  report += formatSection("Audit Trail", audit);

  // Footer
  report += "\n" + "─".repeat(60) + "\n";
  report += "This report was generated by ATLAS Uncertainty Modeling System.\n";
  report += "All probabilities are model estimates and should be interpreted\n";
  report += "in context of the stated confidence levels and data gaps.\n";
  report += "─".repeat(60) + "\n";

  return report;
}

export function ExportReport({ prediction }: Props) {
  const [exporting, setExporting] = useState(false);

  const handleExport = useCallback(() => {
    setExporting(true);
    // Small delay for UX feedback
    setTimeout(() => {
      const report = generateReport(prediction);
      const blob = new Blob([report], { type: "text/plain;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `atlas-report-${prediction.id}-${new Date().toISOString().slice(0, 10)}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      setExporting(false);
    }, 400);
  }, [prediction]);

  return (
    <div className="atlas-panel">
      <div className="flex items-start justify-between">
        <div>
          <h3 className="text-sm font-semibold text-card-foreground">Export Report</h3>
          <p className="text-xs text-muted-foreground mt-0.5">
            Download a full prediction report with metrics, audit trail, and uncertainty analysis
          </p>
        </div>
        <Button
          size="sm"
          variant="outline"
          className="h-8 text-xs gap-1.5 shrink-0"
          onClick={handleExport}
          disabled={exporting}
        >
          {exporting ? (
            <Loader2 className="h-3 w-3 animate-spin" />
          ) : (
            <Download className="h-3 w-3" />
          )}
          {exporting ? "Generating…" : "Download Report"}
        </Button>
      </div>

      {/* Preview snippet */}
      <div className="mt-3 rounded-md bg-secondary/40 border border-border/50 p-3 font-mono text-[10px] text-muted-foreground leading-relaxed max-h-20 overflow-hidden relative">
        <div className="flex items-center gap-1.5 mb-1.5 text-card-foreground">
          <FileText className="h-3 w-3" />
          <span className="text-[10px] font-semibold">Report Preview</span>
        </div>
        <p>{prediction.title} — {prediction.region}</p>
        <p>Probability: {prediction.probability}% | Confidence: {prediction.confidence} | Data: {prediction.dataCompleteness}%</p>
        <p>Models: {(prediction.modelAgreement * 100).toFixed(0)}% agreement | Pop. exposure: {(prediction.populationExposure / 1e6).toFixed(1)}M</p>
        <div className="absolute bottom-0 left-0 right-0 h-6 bg-gradient-to-t from-secondary/40 to-transparent" />
      </div>
    </div>
  );
}
